/*
 * ERZEUGT — nicht von Hand ändern.
 *
 * Quelle: packages/docs/demo/product-catalog/script/Store_Assortment.json
 * Erzeuger: packages/handelswelt/erzeugung/erzeuge.ts
 * Zuordnung echter Marken auf Decknamen: erzeugung/decknamen.ts
 *
 * Warengruppen, Größen und Preislagen stammen aus 92 Regalfotos und sind echt.
 * Die Namen sind es nicht — siehe die Notiz `demo-daten-keine-echten-marken`.
 */

export type Regalzone = 'tafel' | 'riegel' | 'pralinen';

export interface Artikel {
  /** Artikelnummer, wie sie in der Warenwirtschaft steht. */
  readonly nummer: string;
  readonly marke: string;
  readonly bezeichnung: string;
  readonly gramm: number;
  readonly zone: Regalzone;
  /** Eigenmarke der Kette — trägt mehr Rohertrag als eine Herstellermarke. */
  readonly eigenmarke: boolean;
  readonly facings: number;
  /** Absatz der letzten zwölf Monate, ganze Kette, in Stück. */
  readonly absatzJahr: number;
  /** Entwicklung gegenüber dem Vorjahr in Prozent. */
  readonly entwicklung: number;
  readonly ekPreis: number;
  readonly vkPreis: number;
}

/** Die Kategorie, für die Lisa verantwortlich ist. */
export const KATEGORIE = "Schokolade & Pralinen";

export const SORTIMENT: readonly Artikel[] = [
  {
    "nummer": "NK-488778",
    "marke": "Almgold",
    "bezeichnung": "Maxi",
    "gramm": 270,
    "zone": "tafel",
    "eigenmarke": false,
    "facings": 1,
    "absatzJahr": 15400,
    "entwicklung": 6.1,
    "ekPreis": 2.48,
    "vkPreis": 3.5900000000000003
  },
  {
    "nummer": "NK-109915",
    "marke": "Almgold",
    "bezeichnung": "Tafel",
    "gramm": 100,
    "zone": "tafel",
    "eigenmarke": false,
    "facings": 2,
    "absatzJahr": 15800,
    "entwicklung": 3.5,
    "ekPreis": 0.98,
    "vkPreis": 1.49
  },
  {
    "nummer": "NK-791810",
    "marke": "Bambini",
    "bezeichnung": "Carte",
    "gramm": 128,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 3,
    "absatzJahr": 84300,
    "entwicklung": 10.8,
    "ekPreis": 1.1,
    "vkPreis": 1.69
  },
  {
    "nummer": "NK-468156",
    "marke": "Bambini",
    "bezeichnung": "Doppio",
    "gramm": 129,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 4,
    "absatzJahr": 64700,
    "entwicklung": 14.6,
    "ekPreis": 1.2,
    "vkPreis": 1.69
  },
  {
    "nummer": "NK-233399",
    "marke": "Bambini",
    "bezeichnung": "Korn",
    "gramm": 211,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 3,
    "absatzJahr": 40300,
    "entwicklung": 5,
    "ekPreis": 2.08,
    "vkPreis": 2.99
  },
  {
    "nummer": "NK-884861",
    "marke": "Bambini",
    "bezeichnung": "Mix",
    "gramm": 210,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 1,
    "absatzJahr": 39700,
    "entwicklung": 10.7,
    "ekPreis": 1.5,
    "vkPreis": 2.39
  },
  {
    "nummer": "NK-441470",
    "marke": "Bambini",
    "bezeichnung": "Schoko-Eier",
    "gramm": 200,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 3,
    "absatzJahr": 29400,
    "entwicklung": -6.5,
    "ekPreis": 1.98,
    "vkPreis": 2.79
  },
  {
    "nummer": "NK-615404",
    "marke": "Bambini",
    "bezeichnung": "Schokolade",
    "gramm": 300,
    "zone": "tafel",
    "eigenmarke": false,
    "facings": 3,
    "absatzJahr": 82500,
    "entwicklung": -3.6,
    "ekPreis": 1.63,
    "vkPreis": 2.5900000000000003
  },
  {
    "nummer": "NK-698756",
    "marke": "Berghoff",
    "bezeichnung": "Alpenmilch Schokolade",
    "gramm": 300,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 85900,
    "entwicklung": -9.5,
    "ekPreis": 1.77,
    "vkPreis": 2.89
  },
  {
    "nummer": "NK-455451",
    "marke": "Berghoff",
    "bezeichnung": "Choco Wandel",
    "gramm": 150,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 53700,
    "entwicklung": 8.9,
    "ekPreis": 0.93,
    "vkPreis": 1.69
  },
  {
    "nummer": "NK-817022",
    "marke": "Berghoff",
    "bezeichnung": "Chocolat Creation",
    "gramm": 150,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 107800,
    "entwicklung": 10.3,
    "ekPreis": 0.94,
    "vkPreis": 1.59
  },
  {
    "nummer": "NK-815162",
    "marke": "Berghoff",
    "bezeichnung": "Délice",
    "gramm": 182,
    "zone": "pralinen",
    "eigenmarke": true,
    "facings": 2,
    "absatzJahr": 60900,
    "entwicklung": 16.6,
    "ekPreis": 2.02,
    "vkPreis": 3.29
  },
  {
    "nummer": "NK-951914",
    "marke": "Berghoff",
    "bezeichnung": "Edel Bitter 70%",
    "gramm": 125,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 5,
    "absatzJahr": 136200,
    "entwicklung": 2.5,
    "ekPreis": 0.86,
    "vkPreis": 1.59
  },
  {
    "nummer": "NK-809490",
    "marke": "Berghoff",
    "bezeichnung": "Edel Bitter 85%",
    "gramm": 125,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 76700,
    "entwicklung": 11.1,
    "ekPreis": 0.64,
    "vkPreis": 1.19
  },
  {
    "nummer": "NK-525981",
    "marke": "Berghoff",
    "bezeichnung": "Edel Bitter Caramel",
    "gramm": 125,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 5,
    "absatzJahr": 163500,
    "entwicklung": -7.5,
    "ekPreis": 0.86,
    "vkPreis": 1.59
  },
  {
    "nummer": "NK-319453",
    "marke": "Berghoff",
    "bezeichnung": "Edel Bitter Mousse au Chocolat",
    "gramm": 125,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 106100,
    "entwicklung": 9.2,
    "ekPreis": 0.64,
    "vkPreis": 1.19
  },
  {
    "nummer": "NK-385326",
    "marke": "Berghoff",
    "bezeichnung": "Edel Bitter Orange",
    "gramm": 125,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 173900,
    "entwicklung": 9.7,
    "ekPreis": 0.63,
    "vkPreis": 1.19
  },
  {
    "nummer": "NK-199108",
    "marke": "Berghoff",
    "bezeichnung": "Edel Bitter Sauerkirsch-Chili",
    "gramm": 125,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 5,
    "absatzJahr": 85200,
    "entwicklung": 8.8,
    "ekPreis": 0.77,
    "vkPreis": 1.39
  },
  {
    "nummer": "NK-622726",
    "marke": "Berghoff",
    "bezeichnung": "Edel Vollmilch",
    "gramm": 125,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 5,
    "absatzJahr": 140200,
    "entwicklung": 13.2,
    "ekPreis": 0.87,
    "vkPreis": 1.49
  },
  {
    "nummer": "NK-669145",
    "marke": "Berghoff",
    "bezeichnung": "Haselnuss Schokolade",
    "gramm": 300,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 174800,
    "entwicklung": 3.7,
    "ekPreis": 1.51,
    "vkPreis": 2.79
  },
  {
    "nummer": "NK-854050",
    "marke": "Berghoff",
    "bezeichnung": "Himbeer Mousse",
    "gramm": 150,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 108100,
    "entwicklung": -5.6,
    "ekPreis": 0.97,
    "vkPreis": 1.59
  },
  {
    "nummer": "NK-672808",
    "marke": "Berghoff",
    "bezeichnung": "Milchperlen Caramel",
    "gramm": 150,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 169200,
    "entwicklung": 7.9,
    "ekPreis": 0.82,
    "vkPreis": 1.49
  },
  {
    "nummer": "NK-977085",
    "marke": "Berghoff",
    "bezeichnung": "Milchperlen Classic",
    "gramm": 150,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 123600,
    "entwicklung": 7.8,
    "ekPreis": 0.76,
    "vkPreis": 1.39
  },
  {
    "nummer": "NK-527913",
    "marke": "Berghoff",
    "bezeichnung": "Milchperlen Erdbeere",
    "gramm": 150,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 2,
    "absatzJahr": 129400,
    "entwicklung": 14.8,
    "ekPreis": 0.84,
    "vkPreis": 1.39
  },
  {
    "nummer": "NK-612174",
    "marke": "Berghoff",
    "bezeichnung": "Mousse au Lait",
    "gramm": 150,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 147200,
    "entwicklung": -7.1,
    "ekPreis": 0.93,
    "vkPreis": 1.59
  },
  {
    "nummer": "NK-204771",
    "marke": "Berghoff",
    "bezeichnung": "Nocturne Mini",
    "gramm": 160,
    "zone": "riegel",
    "eigenmarke": true,
    "facings": 2,
    "absatzJahr": 41200,
    "entwicklung": -12,
    "ekPreis": 1.44,
    "vkPreis": 2.49
  },
  {
    "nummer": "NK-121094",
    "marke": "Berghoff",
    "bezeichnung": "Pralinés",
    "gramm": 300,
    "zone": "pralinen",
    "eigenmarke": true,
    "facings": 2,
    "absatzJahr": 165500,
    "entwicklung": 4.8,
    "ekPreis": 2.62,
    "vkPreis": 4.49
  },
  {
    "nummer": "NK-109843",
    "marke": "Berghoff",
    "bezeichnung": "Vegane Schokolade Caramel Sea Salt",
    "gramm": 125,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 5,
    "absatzJahr": 126600,
    "entwicklung": 13.1,
    "ekPreis": 0.66,
    "vkPreis": 1.19
  },
  {
    "nummer": "NK-785447",
    "marke": "Berghoff",
    "bezeichnung": "Vegane Schokolade Cookie",
    "gramm": 125,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 164800,
    "entwicklung": 14.2,
    "ekPreis": 0.92,
    "vkPreis": 1.59
  },
  {
    "nummer": "NK-212488",
    "marke": "Berghoff",
    "bezeichnung": "Vegane Schokolade Roasted Salty Almonds",
    "gramm": 125,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 140400,
    "entwicklung": -7.8,
    "ekPreis": 0.84,
    "vkPreis": 1.59
  },
  {
    "nummer": "NK-187691",
    "marke": "Chocorée",
    "bezeichnung": "Alpen Sahne Schokolade",
    "gramm": 200,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 139500,
    "entwicklung": -2.5,
    "ekPreis": 0.89,
    "vkPreis": 1.49
  },
  {
    "nummer": "NK-824605",
    "marke": "Chocorée",
    "bezeichnung": "Alpenmilch Schokolade",
    "gramm": 100,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 2,
    "absatzJahr": 46300,
    "entwicklung": 10.1,
    "ekPreis": 0.53,
    "vkPreis": 0.89
  },
  {
    "nummer": "NK-939207",
    "marke": "Chocorée",
    "bezeichnung": "Buttermilch Lemon",
    "gramm": 200,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 92400,
    "entwicklung": 0.9,
    "ekPreis": 0.73,
    "vkPreis": 1.39
  },
  {
    "nummer": "NK-321355",
    "marke": "Chocorée",
    "bezeichnung": "Choco & Keks",
    "gramm": 300,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 2,
    "absatzJahr": 172500,
    "entwicklung": -1.9,
    "ekPreis": 0.94,
    "vkPreis": 1.59
  },
  {
    "nummer": "NK-215058",
    "marke": "Chocorée",
    "bezeichnung": "Erdbeer Joghurt Schokolade",
    "gramm": 200,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 5,
    "absatzJahr": 138500,
    "entwicklung": 8,
    "ekPreis": 0.66,
    "vkPreis": 1.19
  },
  {
    "nummer": "NK-679462",
    "marke": "Chocorée",
    "bezeichnung": "Feine Mignon-Stäbchen",
    "gramm": 300,
    "zone": "riegel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 81500,
    "entwicklung": -7.2,
    "ekPreis": 1.1,
    "vkPreis": 1.99
  },
  {
    "nummer": "NK-157700",
    "marke": "Chocorée",
    "bezeichnung": "Feine Sahne Schokolade",
    "gramm": 200,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 77600,
    "entwicklung": 3.6,
    "ekPreis": 0.72,
    "vkPreis": 1.19
  },
  {
    "nummer": "NK-295918",
    "marke": "Chocorée",
    "bezeichnung": "Haselnuss Schokolade",
    "gramm": 100,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 5,
    "absatzJahr": 72400,
    "entwicklung": 3.1,
    "ekPreis": 0.43,
    "vkPreis": 0.79
  },
  {
    "nummer": "NK-720494",
    "marke": "Chocorée",
    "bezeichnung": "Joghurt",
    "gramm": 200,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 2,
    "absatzJahr": 129300,
    "entwicklung": 9.3,
    "ekPreis": 0.68,
    "vkPreis": 1.29
  },
  {
    "nummer": "NK-671147",
    "marke": "Chocorée",
    "bezeichnung": "Kaffee Sahne Schokolade",
    "gramm": 200,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 148300,
    "entwicklung": -0.8,
    "ekPreis": 0.94,
    "vkPreis": 1.59
  },
  {
    "nummer": "NK-584641",
    "marke": "Chocorée",
    "bezeichnung": "Knusper Riegel",
    "gramm": 200,
    "zone": "riegel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 171600,
    "entwicklung": 15.6,
    "ekPreis": 1.05,
    "vkPreis": 1.79
  },
  {
    "nummer": "NK-206110",
    "marke": "Chocorée",
    "bezeichnung": "Korn & Schoko",
    "gramm": 200,
    "zone": "riegel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 162000,
    "entwicklung": -2.5,
    "ekPreis": 0.97,
    "vkPreis": 1.79
  },
  {
    "nummer": "NK-273625",
    "marke": "Chocorée",
    "bezeichnung": "Mandelknacker",
    "gramm": 100,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 141500,
    "entwicklung": -9.6,
    "ekPreis": 0.46,
    "vkPreis": 0.79
  },
  {
    "nummer": "NK-180287",
    "marke": "Chocorée",
    "bezeichnung": "Milch Jumbo Riegel",
    "gramm": 300,
    "zone": "riegel",
    "eigenmarke": true,
    "facings": 5,
    "absatzJahr": 110500,
    "entwicklung": 1.3,
    "ekPreis": 1.11,
    "vkPreis": 1.89
  },
  {
    "nummer": "NK-877226",
    "marke": "Chocorée",
    "bezeichnung": "Milch Riegel",
    "gramm": 300,
    "zone": "riegel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 143100,
    "entwicklung": 3.2,
    "ekPreis": 1.34,
    "vkPreis": 2.49
  },
  {
    "nummer": "NK-247754",
    "marke": "Chocorée",
    "bezeichnung": "Mini Schokoladen-Riegel",
    "gramm": 200,
    "zone": "riegel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 57300,
    "entwicklung": -7.6,
    "ekPreis": 0.84,
    "vkPreis": 1.39
  },
  {
    "nummer": "NK-839880",
    "marke": "Chocorée",
    "bezeichnung": "Nussbeißer",
    "gramm": 100,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 150200,
    "entwicklung": 10.7,
    "ekPreis": 0.47,
    "vkPreis": 0.79
  },
  {
    "nummer": "NK-261299",
    "marke": "Chocorée",
    "bezeichnung": "Nussknacker",
    "gramm": 100,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 144800,
    "entwicklung": 9.9,
    "ekPreis": 0.58,
    "vkPreis": 0.99
  },
  {
    "nummer": "NK-699029",
    "marke": "Chocorée",
    "bezeichnung": "Rahm Mandel Schokolade",
    "gramm": 200,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 157800,
    "entwicklung": -5.2,
    "ekPreis": 0.65,
    "vkPreis": 1.19
  },
  {
    "nummer": "NK-332221",
    "marke": "Chocorée",
    "bezeichnung": "Rosinen & Nuss Schokolade",
    "gramm": 200,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 161700,
    "entwicklung": 15.3,
    "ekPreis": 0.82,
    "vkPreis": 1.39
  },
  {
    "nummer": "NK-474864",
    "marke": "Chocorée",
    "bezeichnung": "Schoko & Keks Riegel",
    "gramm": 300,
    "zone": "riegel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 149400,
    "entwicklung": -1.4,
    "ekPreis": 1.45,
    "vkPreis": 2.39
  },
  {
    "nummer": "NK-751724",
    "marke": "Chocorée",
    "bezeichnung": "Schoko Riegel",
    "gramm": 200,
    "zone": "riegel",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 50800,
    "entwicklung": -6.5,
    "ekPreis": 0.76,
    "vkPreis": 1.39
  },
  {
    "nummer": "NK-995704",
    "marke": "Chocorée",
    "bezeichnung": "Schoko Rosinen",
    "gramm": 200,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 2,
    "absatzJahr": 167700,
    "entwicklung": -7.9,
    "ekPreis": 0.61,
    "vkPreis": 1.09
  },
  {
    "nummer": "NK-922459",
    "marke": "Chocorée",
    "bezeichnung": "Schokoküsse groß",
    "gramm": 360,
    "zone": "pralinen",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 157700,
    "entwicklung": 12.1,
    "ekPreis": 2.15,
    "vkPreis": 3.79
  },
  {
    "nummer": "NK-634727",
    "marke": "Chocorée",
    "bezeichnung": "Schokoküsse mini",
    "gramm": 266,
    "zone": "pralinen",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 124500,
    "entwicklung": -2.1,
    "ekPreis": 1.34,
    "vkPreis": 2.49
  },
  {
    "nummer": "NK-259191",
    "marke": "Chocorée",
    "bezeichnung": "Spaghetti-Eis Schokolade",
    "gramm": 100,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 50100,
    "entwicklung": 16.3,
    "ekPreis": 0.46,
    "vkPreis": 0.79
  },
  {
    "nummer": "NK-362808",
    "marke": "Chocorée",
    "bezeichnung": "Trüffel",
    "gramm": 200,
    "zone": "pralinen",
    "eigenmarke": true,
    "facings": 3,
    "absatzJahr": 163900,
    "entwicklung": 9.8,
    "ekPreis": 1.35,
    "vkPreis": 2.49
  },
  {
    "nummer": "NK-266353",
    "marke": "Chocorée",
    "bezeichnung": "Weiße Schokolade",
    "gramm": 200,
    "zone": "tafel",
    "eigenmarke": true,
    "facings": 4,
    "absatzJahr": 101900,
    "entwicklung": -3.3,
    "ekPreis": 0.78,
    "vkPreis": 1.29
  },
  {
    "nummer": "NK-522896",
    "marke": "Hallbach",
    "bezeichnung": "Häppchen",
    "gramm": 180,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 3,
    "absatzJahr": 56700,
    "entwicklung": -7,
    "ekPreis": 1.31,
    "vkPreis": 1.99
  },
  {
    "nummer": "NK-428805",
    "marke": "Hallbach",
    "bezeichnung": "Karamellknopf",
    "gramm": 125,
    "zone": "pralinen",
    "eigenmarke": false,
    "facings": 2,
    "absatzJahr": 62200,
    "entwicklung": 14.2,
    "ekPreis": 1.77,
    "vkPreis": 2.79
  },
  {
    "nummer": "NK-842671",
    "marke": "Hallbach",
    "bezeichnung": "Karamellknopf Weiß",
    "gramm": 125,
    "zone": "pralinen",
    "eigenmarke": false,
    "facings": 2,
    "absatzJahr": 16400,
    "entwicklung": -6.1,
    "ekPreis": 1.37,
    "vkPreis": 2.0900000000000003
  },
  {
    "nummer": "NK-748301",
    "marke": "Hallbach",
    "bezeichnung": "Kokosriegel",
    "gramm": 200,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 2,
    "absatzJahr": 66100,
    "entwicklung": -10.6,
    "ekPreis": 2.02,
    "vkPreis": 2.99
  },
  {
    "nummer": "NK-373531",
    "marke": "Hallbach",
    "bezeichnung": "Nussriegel",
    "gramm": 200,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 3,
    "absatzJahr": 24400,
    "entwicklung": 5.3,
    "ekPreis": 1.36,
    "vkPreis": 2.1900000000000004
  },
  {
    "nummer": "NK-877492",
    "marke": "Hallbach",
    "bezeichnung": "Nussriegel Zartbitter",
    "gramm": 200,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 1,
    "absatzJahr": 50700,
    "entwicklung": -7.4,
    "ekPreis": 1.63,
    "vkPreis": 2.39
  },
  {
    "nummer": "NK-729238",
    "marke": "Hallbach",
    "bezeichnung": "Selection Crocant",
    "gramm": 225,
    "zone": "pralinen",
    "eigenmarke": false,
    "facings": 2,
    "absatzJahr": 47100,
    "entwicklung": 3.8,
    "ekPreis": 2.8,
    "vkPreis": 4.09
  },
  {
    "nummer": "NK-554312",
    "marke": "Hallbach",
    "bezeichnung": "Selection Fein",
    "gramm": 250,
    "zone": "pralinen",
    "eigenmarke": false,
    "facings": 1,
    "absatzJahr": 55300,
    "entwicklung": 2.7,
    "ekPreis": 2.16,
    "vkPreis": 3.49
  },
  {
    "nummer": "NK-185883",
    "marke": "Hallbach",
    "bezeichnung": "Selection Petits",
    "gramm": 185,
    "zone": "pralinen",
    "eigenmarke": false,
    "facings": 2,
    "absatzJahr": 85400,
    "entwicklung": 8.6,
    "ekPreis": 2.43,
    "vkPreis": 3.79
  },
  {
    "nummer": "NK-341555",
    "marke": "Hallbach",
    "bezeichnung": "Täfelchen",
    "gramm": 325,
    "zone": "pralinen",
    "eigenmarke": false,
    "facings": 2,
    "absatzJahr": 87500,
    "entwicklung": -8.4,
    "ekPreis": 3.54,
    "vkPreis": 5.19
  },
  {
    "nummer": "NK-785818",
    "marke": "Hallbach",
    "bezeichnung": "Täfelchen Minze",
    "gramm": 325,
    "zone": "pralinen",
    "eigenmarke": false,
    "facings": 2,
    "absatzJahr": 21000,
    "entwicklung": 17.2,
    "ekPreis": 2.74,
    "vkPreis": 3.89
  },
  {
    "nummer": "NK-691223",
    "marke": "Hallbach",
    "bezeichnung": "Waffelschnitte",
    "gramm": 200,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 3,
    "absatzJahr": 85000,
    "entwicklung": 0.6,
    "ekPreis": 1.51,
    "vkPreis": 2.29
  },
  {
    "nummer": "NK-323490",
    "marke": "Helvetia",
    "bezeichnung": "Knusperkreuz",
    "gramm": 150,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 3,
    "absatzJahr": 53500,
    "entwicklung": 2.2,
    "ekPreis": 1.27,
    "vkPreis": 1.79
  },
  {
    "nummer": "NK-941680",
    "marke": "Korngold",
    "bezeichnung": "Joghurt-Beere",
    "gramm": 185,
    "zone": "tafel",
    "eigenmarke": false,
    "facings": 1,
    "absatzJahr": 34400,
    "entwicklung": 8.8,
    "ekPreis": 1.74,
    "vkPreis": 2.49
  },
  {
    "nummer": "NK-897289",
    "marke": "Korngold",
    "bezeichnung": "Korn",
    "gramm": 185,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 3,
    "absatzJahr": 80200,
    "entwicklung": -2.6,
    "ekPreis": 1.57,
    "vkPreis": 2.29
  },
  {
    "nummer": "NK-542260",
    "marke": "Nussberg",
    "bezeichnung": "Riegel",
    "gramm": 150,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 3,
    "absatzJahr": 67500,
    "entwicklung": -9.8,
    "ekPreis": 1.24,
    "vkPreis": 1.79
  },
  {
    "nummer": "NK-306753",
    "marke": "Torretta",
    "bezeichnung": "Duetto",
    "gramm": 182,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 2,
    "absatzJahr": 62100,
    "entwicklung": 9.9,
    "ekPreis": 1.81,
    "vkPreis": 2.5900000000000003
  },
  {
    "nummer": "NK-489535",
    "marke": "Torretta",
    "bezeichnung": "Fruttella",
    "gramm": 125,
    "zone": "tafel",
    "eigenmarke": false,
    "facings": 1,
    "absatzJahr": 76900,
    "entwicklung": 6.6,
    "ekPreis": 0.9,
    "vkPreis": 1.29
  },
  {
    "nummer": "NK-642873",
    "marke": "Torretta",
    "bezeichnung": "Nusstafel",
    "gramm": 220,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 2,
    "absatzJahr": 33600,
    "entwicklung": 7.6,
    "ekPreis": 2,
    "vkPreis": 2.89
  },
  {
    "nummer": "NK-214650",
    "marke": "Torretta",
    "bezeichnung": "Riegel",
    "gramm": 210,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 2,
    "absatzJahr": 68700,
    "entwicklung": -4.1,
    "ekPreis": 1.82,
    "vkPreis": 2.89
  },
  {
    "nummer": "NK-883495",
    "marke": "Torretta",
    "bezeichnung": "Schokolade",
    "gramm": 100,
    "zone": "tafel",
    "eigenmarke": false,
    "facings": 1,
    "absatzJahr": 24100,
    "entwicklung": -7.9,
    "ekPreis": 0.8,
    "vkPreis": 1.19
  },
  {
    "nummer": "NK-507730",
    "marke": "Torretta",
    "bezeichnung": "Tondo",
    "gramm": 154,
    "zone": "pralinen",
    "eigenmarke": false,
    "facings": 1,
    "absatzJahr": 77100,
    "entwicklung": -10.5,
    "ekPreis": 1.98,
    "vkPreis": 3.0900000000000003
  },
  {
    "nummer": "NK-443798",
    "marke": "Vega",
    "bezeichnung": "Buntlinsen Erdnuss",
    "gramm": 300,
    "zone": "riegel",
    "eigenmarke": false,
    "facings": 3,
    "absatzJahr": 38800,
    "entwicklung": -2.3,
    "ekPreis": 2.45,
    "vkPreis": 3.89
  }
];
