import fc from "fast-check";
import { describe, it, expect } from "vitest";
import type { SimEvent } from "./orchestrator.js";
import {
  SortimentsplanungAgent,
  EinkaufAgent,
  ScCoordinatorAgent,
  LogistikAgent,
  FilialnachbestellungAgent,
} from "./agents/index.js";

/**
 * **Validates: Requirements 13.1**
 *
 * Property 6: Interne Nachrichten verwenden ALDI-Mailadresse
 *
 * For every Outlook message generated by an internal role agent (not Lieferant):
 * The sender address matches the format vorname.nachname@aldi-sued.de.
 */
describe("Feature: supply-chain-simulation, Property 6: Interne Nachrichten verwenden ALDI-Mailadresse", () => {
  const internalAgents = [
    new SortimentsplanungAgent(),
    new EinkaufAgent(),
    new ScCoordinatorAgent(),
    new LogistikAgent(),
    new FilialnachbestellungAgent(),
  ];

  /**
   * Arbitrary for generating valid SimEvent objects with various types
   * that internal agents can handle.
   */
  const simEventArb = fc
    .record({
      id: fc.integer({ min: 1, max: 10000 }),
      timestamp: fc
        .date({ min: new Date("2024-01-01"), max: new Date("2026-12-31") })
        .map((d) => d.toISOString()),
      type: fc.constantFrom("disruption", "escalation", "kpi_alert"),
      source_role: fc.constantFrom(
        "system",
        "buyer",
        "sc_coordinator",
        "logistics",
      ),
      target_role: fc.constantFrom(
        null,
        "buyer",
        "sc_coordinator",
        "logistics",
        "assortment_planning",
        "store_replenishment",
      ),
      scenario_id: fc.constantFrom(null, "scenario_1", "scenario_2"),
      status: fc.constant("pending"),
    })
    .chain((base) => {
      // Generate appropriate payloads based on event type
      const payloadArb =
        base.type === "disruption"
          ? fc.record({
              type: fc.constantFrom(
                "lieferausfall",
                "rueckruf",
                "streik",
                "naturkatastrophe",
              ),
              affected_skus: fc.array(fc.stringMatching(/^SKU-[0-9]{4}$/), {
                minLength: 1,
                maxLength: 5,
              }),
              duration: fc.integer({ min: 1, max: 30 }),
              margin_impact: fc.integer({ min: 10, max: 200 }),
            })
          : base.type === "escalation"
            ? fc.record({
                level: fc.constantFrom(1, 2, 3),
                trigger_kpi: fc.constantFrom(
                  "otd",
                  "osa",
                  "cost_deviation",
                  "mape",
                ),
                trigger_value: fc.float({ min: 0, max: 1, noNaN: true }),
                threshold: fc.float({ min: 0, max: 1, noNaN: true }),
              })
            : fc.record({
                kpi_name: fc.constantFrom(
                  "otd",
                  "osa",
                  "cost_deviation",
                  "mape",
                  "coverage_days",
                ),
                value: fc.float({ min: 0, max: 1, noNaN: true }),
              });

      return payloadArb.map((payload) => ({
        ...base,
        payload: JSON.stringify(payload),
      }));
    });

  const ALDI_MAIL_REGEX = /^[a-z]+\.[a-z]+@aldi-sued\.de$/;

  it("all outlook messages from internal agents have sender matching vorname.nachname@aldi-sued.de", () => {
    fc.assert(
      fc.asyncProperty(simEventArb, async (event: SimEvent) => {
        for (const agent of internalAgents) {
          // Only process events that match the agent's configured eventTypes
          if (!agent.config.eventTypes.includes(event.type)) {
            continue;
          }

          const actions = await agent.handleEvent(event);

          for (const action of actions) {
            if (action.type === "message") {
              const payload = action.payload as {
                channel: string;
                sender: string;
              };

              if (payload.channel === "outlook") {
                expect(payload.sender).toMatch(ALDI_MAIL_REGEX);
              }
            }
          }
        }
      }),
      { numRuns: 100 },
    );
  });
});
